# Generated by Django 5.2.4 on 2025-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_remove_book_publication_year_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
